ImageStore/Models/Entity/Image.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ImageStore.Models
{
    public class Image
    {
        public int ImageID { get; set; }
        public byte[] Picture { get; set; }
        
        public DateTime DatePublishing { get; set; }

        public double? Latitude { get; set; }
        public double? Longitude { get; set; }

        [MaxLength(100)]
        public string Comment { get; set; }

        [MaxLength(30)]
        public string Name { get; set; }

        public int CategoryID { get; set; }
        public double Rating { get; set; }
        public string UserID { get; set; }
        public bool IsDeleted { get; set; }
        public int CountryID { get; set; }
        public string PictureMimeType { get; set; }
    }
}

ImageStore/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImageStore.Infrastructure;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using ImageStore.Models;
using System.Threading.Tasks;

namespace ImageStore.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {

        ImageRepository repo = new ImageRepository();
        public int pageSize = 5;

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }
        [AllowAnonymous]
        public ActionResult List(int ImageID, int page = 1)
        {
            
            ListViewModel<CommentView> model = new ListViewModel<CommentView>();

            IEnumerable<Comment> comments = repo.Comments
            .Where(p => p.ImageID == ImageID && p.IsDeleted == false)
            .OrderBy(im => im.DatePublishing)
            .Skip((page - 1) * pageSize)
            .Take(pageSize);
            List<CommentView> lc = new List<CommentView>();

            foreach (Comment com in comments)
            {
                CommentView cv = new CommentView();
                cv.Text = com.Text;
                if (UserManager.FindById(com.UserID) != null)
                    cv.UserName = UserManager.FindById(com.UserID).UserName;
                else
                    cv.UserName = "Гость";
                cv.CommentID = com.CommentID;
                cv.DatePubishing = com.DatePublishing;
                cv.UserID = com.UserID;
                lc.Add(cv);
            }
            model.Items = lc;

            model.image = repo.Images.FirstOrDefault(x => x.ImageID == ImageID);

            model.PagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = model.Items.Count()
            };
            return PartialView(model);
        }

        
        [HttpPost]
        public ActionResult Delete(int CommentID, int page = 1)
        {
            
            Comment com = repo.Comments.FirstOrDefault(x => x.CommentID == CommentID);
            com.IsDeleted = true;
            repo.SaveComment(com);
            return RedirectToAction("Index","Image", new { imageID = com.ImageID });
        }

       
        public ActionResult AddComment(int imageid)
        {
            Comment model = new Comment();
            model.ImageID = imageid;
            model.Text = " ";
            return PartialView(model);
        }

     
        [HttpPost]
        public ActionResult AddComment(int imageid, string text)
        {
            string userid = User.Identity.GetUserId();
            repo.SaveComment(new Comment { UserID = userid, ImageID = imageid,
                DatePublishing = DateTime.Now, IsDeleted = false, Text = text});

            return RedirectToAction("Index", "Image", new { imageID = imageid });
        }
    }
}

ImageStore/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImageStore.Infrastructure;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using ImageStore.Models;
using System.Threading.Tasks;

namespace ImageStore.Controllers
{

    public class ImageController : Controller
    {
        ImageRepository repo = new ImageRepository();
        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }


        public ActionResult Index(int imageID, int page = 1)
        {
            ListViewModel<CommentView> lc = new ListViewModel<CommentView>();
            lc.image = repo.Images.FirstOrDefault(c => c.ImageID == imageID);
            lc.PagingInfo = new PagingInfo { CurrentPage = page };
            return View(lc);
        }

        public ActionResult gps(int ImageID)
        {
            Image im = repo.Images.FirstOrDefault(x => x.ImageID == ImageID);

            return View(im);
        }

    }
}

ImageStore/Controllers/NavController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImageStore.Models;
using System.Collections.Generic;
using System.IO;
using ImageStore.Infrastructure;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;

namespace ImageStore.Controllers
{
    [Authorize]
    public class NavController : Controller
    {
        private ImageRepository repo = new ImageRepository();

        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }

        [AllowAnonymous]
        public PartialViewResult Menu(int category = 0, string userid = "")
        {
            ViewBag.currentuser = userid;
            ViewBag.SelectedCategory = category;
            List<Category> categories = new List<Category>();

            foreach(Category c in repo.Catrgories)
            {
                Category cat = new Category() { Name = c.Name, CategoryID=c.CategoryID };
                categories.Add(cat);
            }

            return PartialView(categories);
        }

        public PartialViewResult ImageMenu(int imageid)
        {
            Image im = repo.Images.FirstOrDefault(x => x.ImageID == imageid);
            return PartialView(im);
        }

        public ActionResult Delete(int imageid)
        {
            Image im = repo.Images.FirstOrDefault(x => x.ImageID == imageid);
            if (im != null)
            {
                im.IsDeleted = true;
            }
            repo.SaveImage(im);
            return RedirectToAction("List", "Home");
        }

        public ActionResult Create()
        {
            
            EditViewModel model = new EditViewModel();
            IEnumerable<Category> c = repo.Catrgories;
            model.Categories = from cat in c
                               select new SelectListItem { Text = cat.Name, Value = cat.CategoryID.ToString() };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase image = null)
        {
            Stream str;
            if (image != null)
            {
                Image im = new Image();
                im.PictureMimeType = image.ContentType;
                im.Picture = new byte[image.ContentLength];
                image.InputStream.Read(im.Picture, 0, image.ContentLength);
                image.InputStream.Position = 0;
                str = image.InputStream;
                EXIFHelper exif = new EXIFHelper(str);
                im.Latitude = exif.Latitude;
                im.Longitude = exif.Longitude;
                im.Comment = exif.Comment;
                im.DatePublishing = DateTime.Now;

                ImageRepository repo = new ImageRepository();
                Category c = repo.Catrgories.Last();
                im.CategoryID = c.CategoryID;
                im.UserID = User.Identity.GetUserId(); 
                repo.SaveImage(im);
            }
            return RedirectToAction("List", "Home");
        }

        public ActionResult Edit(int imageid)
        {
            Image im;
            if (imageid == 0)
                im = new Image();
            else
                im = repo.Images.FirstOrDefault(x => x.ImageID == imageid);
            EditViewModel model = new EditViewModel();
            model.image = im;
            IEnumerable<Category> c = repo.Catrgories;

            model.Categories = from cat in c
                           select new SelectListItem { Text = cat.Name, Value = cat.CategoryID.ToString() };

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditViewModel ev)
        {
            Image im = repo.Images.FirstOrDefault(x => x.ImageID == ev.image.ImageID);
            im.Name = ev.image.Name;
            im.CategoryID = ev.image.CategoryID;
            repo.SaveImage(im);
            return RedirectToAction("Index", "Image", new { imageID = im.ImageID });
        }
    }
}

ImageStore/Views/Image/Index.cshtml
@using Microsoft.AspNet.Identity
@using ImageStore.HtmlHelpers
@using ImageStore.Models

@model ImageStore.Models.ListViewModel<CommentView>


@{
    ViewBag.Title = "Index";
}
<div class="row panel">

    @if (!((!Request.IsAuthenticated) || (User.IsInRole("User") && User.Identity.GetUserId() != Model.image.UserID)))
    {

    <div class="navbar-fixed-top">
        <div style="height:60px"></div>
        <div id="categories" class="col-sm-2 hidden-xs">
            @Html.Action("ImageMenu", "Nav")
        </div>
    </div>
    }
    <img class="img-thumbnail" width="500" height="500"
         src="@Url.Action("GetPicture", "Home",
                new {imageId = Model.image.ImageID })" />
    <div class="pull-right">
        <div class="well">
            <h3>Название: @Model.image.Name</h3>
            <h4>Комментарий к снимку: @Model.image.Comment</h4>
            <h5>Дата публикации: @Model.image.DatePublishing</h5>
            @Html.RouteLink("Показать на карте", new
            {
                controller = "Image",
                action = "gps",
                ImageID = Model.image.ImageID
            }, new
            {
                @class = "btn btn-success"
            })
            <h6></h6>
        </div>
     </div>
</div>
<h1></h1>
<h1></h1>
<div id="comments" class="panel panel-primary" >
    <div class="panel-heading">Комментарии</div>
    <div class="panel-body">
        @Html.Action("List", "Comments", new { ImageID = Model.image.ImageID, page = Model.PagingInfo.CurrentPage})
    </div>
</div>
@if (Request.IsAuthenticated)
{
    @Html.Action("AddComment", "Comments", new { imageid = Model.image.ImageID })
}

ImageStore/Views/Image/gps.cshtml
@model ImageStore.Models.Image

@{
    ViewBag.Title = "gps";
}
<script src="http://maps.google.com/maps/api/js?key=AIzaSyDzgtyCIaSuICf0yrWyCjHAbGVllw3yd4k" type="text/javascript"></script>

<div id="canvas" style="height: 600px; width:600px;"></div>
<div class="hidden">
    <input type="text" id="lat" value=@Model.Latitude />
    <input type="text" id="lng" value=@Model.Longitude />
</div>

@section scripts {
    <script type="text/javascript">

    $(document).ready(function () {
        GetMap();
    });
    function GetMap() {
        var lat = parseFloat(($("#lat").val()).replace(",", "."));
        var lng = parseFloat(($("#lng").val()).replace(",", "."));
        google.maps.visualRefresh = true;

        var point = new google.maps.LatLng(lat, lng);

        var mapOptions = {
            zoom: 15,
            center: point,
            mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
        };
        var map = new google.maps.Map(document.getElementById("canvas"), mapOptions);
       
                var marker = new google.maps.Marker({
                    'position': new google.maps.LatLng(lat, lng),
                    'map': map
                });
               marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')
    }
    </script>
}